linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 30
  maligned:
    suggest-new: true

linters:
  disable-all: true
  enable:
    - goimports
    - bodyclose
    - deadcode
    - errcheck
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - golint
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
