version: "2"

linters:
  default: standard
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports
