name: 'tparagen'
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v5
      - name: set up
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: test
        run: go test ./... -v

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
